name: betamax
description: >
  Record your test suite's HTTP interactions and replay them during future test
  runs for fast, deterministic, accurate tests.

  Like Ruby's VCR gem!
version: 2.0.0
repository: https://github.com/shyndman/betamax

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.5
  meta: ^1.7.0
  nock: ^1.2.1
  path: ^1.8.1
  lints: ^2.0.0
  slugify_string: ^2.0.0
  stack_trace: ^1.10.0
  test_api: ^0.4.9
  test: ^1.21.1
